name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24
  - pandas=2.0
  - tensorflow=2.13
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - albumentations==1.4.18
      - pyimagej
